# Server port (change here if 8080 is already in use)
server.port=8090

# Logging (Hands on 3 - Spring Core - Incorporate Logging)
logging.level.org.springframework=info
logging.level.com.cognizant.springlearn=debug
logging.pattern.console=%d{yyMMdd}|%d{HH:mm:ss.SSS}|%-20.20thread|%5p|%-25.25logger{25}|%25M|%m%n
